apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chrome-switches.github.io
  description: "The provided content, \\\"# chrome-switches.github.io\\\", refers to a GitHub Pages website dedicated to Chrome switches."
  annotations:
    github.com/project-slug: sparksis/chrome-switches.github.io
spec:
  type: service
  lifecycle: experimental
  owner: sparksis