apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chrome-switches.github.io
  description: "The content `# chrome-switches.github.io` is a title, likely indicating a website or repository related to Chrome switches."
  annotations:
    github.com/project-slug: sparksis/chrome-switches.github.io
spec:
  type: service
  lifecycle: experimental
  owner: sparksis